config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  get 'home/search'
  get 'home/get_pdf'
  get 'home/get_zip'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def search
    begin
      stars = Github.instance.get_stars_contributors params[:repo]
      render partial: "home/stars_list", locals: { stars: stars }
    rescue Exception => e
      render partial: "home/stars_error", locals: { message: e.message }
    end
  end

  def get_pdf
    pdf = PdfGenerator.generate_star_pdf(params)
    respond_to do |format|
      format.pdf { send_data(pdf, filename: "#{params[:star]}.pdf", type: 'application/pdf') }
    end
  end

  def get_zip
    zip = ZipGenerator.generate_stars_zip(params[:stars])
    zip.rewind
    respond_to do |format|
      format.zip { send_data(zip.read, filename: "all.zip", type: 'application/zip') }
    end
  end

  private

  def user_params
    params.permit!#(:repo, :star, :stars, :place)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_search_form.html.erb
<h1>GitHub Repo Stars</h1>
<br>
<%= form_tag home_search_path, method: 'get', 'data-turbo-frame' => 'stars-list' do %>
  <div class="input-group w-50">
    <span class="input-group-text">Repository</span>
    <%= text_field_tag 'repo', '', placeholder: 'rubygems/rubygems', class: 'form-control', required: true %>
    <%= submit_tag "Search", class: 'btn btn-outline-primary' %>
  </div>
<% end %>

app/views/home/_stars_error.html.erb
<%= turbo_frame_tag 'stars-list' do %>
  <%= message %>
<% end %>

app/views/home/_stars_list.html.erb
<%= turbo_frame_tag 'stars-list' do %>
  <div class="card w-50">
    <div class="card-body">
      <h5 class="card-title text-center">Best contributors</h5>
  <% stars.present? && stars.each_with_index do |star, index| %>
    <div class="row justify-content-around">
      <div class="col-3">
        <% place = index + 1 %>
        <%= "#{place}. #{star}" %>
      </div>
      <div class="col-3">
        <%= link_to icon('fa-regular', 'file-pdf'), :action => "get_pdf", :star => star, :place => place, :format => 'pdf' %>
      </div>
    </div>
  <% end %>
  <div class="text-center">
      <%= link_to "Download ZIP", { :action => "get_zip", :stars => stars, :format => 'zip' }, class: 'btn btn-outline-primary' %>
  </div>
    </div>
  </div>
<% end %>

app/views/home/index.html.erb
<%= turbo_frame_tag 'search-repo-form' do %>
  <%= render 'search_form' %>
<% end %>
<br>
<%= turbo_frame_tag 'stars-list'%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Github Stars</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link rel="icon" href="/public/favicon.svg">
  </head>

  <body>
  <div class="container">
    <%= yield %>
  </div>
  </body>
</html>